### ISSUE TITLE
memory.limit_in_bytes: invalid argument

### ISSUE THREAD

**Issue by yepengxj** [asiainfoLDP/datafoundry-troubleshooting#20]
Error: build error: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-d5575f3a3927ce1c81ba1fea5d5a4f5fc7d70edd1e8d9b64180b8a10261eb777.scope/memory.limit_in_bytes: invalid argument

openshift-origin 1.1.4 bug，据1.1.5 release node可以看到会修改这个问题。
临时可以通过在build过程中显式声明资源配额可以绕过这个问题
```
spec:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
```
