### ISSUE TITLE
docker pull无法从router的443端口执行

### ISSUE THREAD

**Issue by zonesan** [asiainfoLDP/datafoundry-troubleshooting#33]
* 现象： docker v1.11.0执行docker pull时，router返回50x错误。
* 原因： router没有配置为支持https。
* 解决方法： 配置router同时支持80和443(加密)的访问。此解决方案适用于所有需要https访问的route。
* 示例：
```yaml
apiVersion: v1
kind: Route
metadata:
  labels:
    docker-registry: default
  name: docker-registry
spec:
  host: registry.example.com
  port:
    targetPort: 5000-tcp
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: docker-registry
```
